dist: focal
language: node_js
node_js: '18'
services: mysql
before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS testing;'
    - mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'mypass'"
